train: /content/drive/MyDrive/small_object_detection/threshold_labels/t50/folds/fold1/images/train
val: /content/drive/MyDrive/small_object_detection/threshold_labels/t50/folds/fold1/images/val

nc: 4
names: ["fly", "fish", "honeybee", "seagull"]
