nc: 4
names: ['fish', 'fly', 'honeybee', 'seagull']

train: /content/drive/MyDrive/small_object_detection/original/folds/fold1/images/train
val:  /content/drive/MyDrive/small_object_detection/original/folds/fold1/images/val

